name: Saphan
options:
  bundleIdPrefix: com.krsnalabs
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  postGenCommand: pod install

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"

targets:
  Saphan:
    type: application
    platform: iOS
    sources:
      - path: Saphan
    dependencies:
      - target: SaphanCore
      - target: SaphanKeyboard
      - package: Supabase
      - package: RevenueCat
      - package: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.krsnalabs.saphan
        INFOPLIST_FILE: Saphan/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Saphan/Supporting/Saphan.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Saphan/Supporting/Saphan.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.krsnalabs.saphan
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.krsnalabs.saphan

  SaphanKeyboard:
    type: app-extension
    platform: iOS
    sources:
      - path: SaphanKeyboard
    dependencies:
      - target: SaphanCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.krsnalabs.saphan.keyboard
        INFOPLIST_FILE: SaphanKeyboard/Info.plist
        CODE_SIGN_ENTITLEMENTS: SaphanKeyboard/SaphanKeyboard.entitlements
    entitlements:
      path: SaphanKeyboard/SaphanKeyboard.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.krsnalabs.saphan
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.krsnalabs.saphan

  SaphanCore:
    type: framework
    platform: iOS
    sources:
      - path: SaphanCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.krsnalabs.saphan.core
        GENERATE_INFOPLIST_FILE: true
        BUILD_LIBRARY_FOR_DISTRIBUTION: true

  SaphanTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SaphanTests
    dependencies:
      - target: Saphan
      - target: SaphanCore

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    from: "4.0.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"
